version: '3.8'

services:
  fastapi:
    build: ./app
    ports:
      - "1111:1111"
    environment:
      - DB_URL=mongodb://db/myMongoDb
    volumes:
      - ./app:/app

  db:
    image: mongo
    ports:
      - 27018:27018
    volumes:
      - taskdb:/data/db

volumes:
  taskdb:
